project_id = "nbjoqsaeulvwxlnbevog"

[functions.allocate-activities]
verify_jwt = true

[functions.generate-weekly-summary]
verify_jwt = true

[functions.activity-chatbot]
verify_jwt = false

[functions.generate-pdf-report]
verify_jwt = true

[functions.import-students]
verify_jwt = false

[functions.import-teachers]
verify_jwt = false

[functions.google-calendar-sync]
verify_jwt = false
